/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'ext_przemyslaw.galaz' at '21.03.14 13:57' with Gradle 1.11
 *
 * @author ext_przemyslaw.galaz, @date 21.03.14 13:57
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
