/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'ext_przemyslaw.galaz' at '21.03.14 13:57' with Gradle 1.11
 *
 * @author ext_przemyslaw.galaz, @date 21.03.14 13:57
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
